services:
    backend_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_api
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - mysql-app
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - backend_app
    mysql-app:
        image: mysql:8.0
        container_name: laravel_mysql
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel_network
volumes:
    mysql_data:
# Define redes para os containers
networks:
    # Cria uma rede chamada app-network do tipo bridge para interligar os containers
    laravel_network:
        driver: bridge
