services:
    backend_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_api
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - postgres_app
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8080:8080"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - backend_app
    postgres_app:
        image: postgres:15
        container_name: laravel_postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel_network
volumes:
    postgres_data:
# Define redes para os containers
networks:
    # Cria uma rede chamada app-network do tipo bridge para interligar os containers
    laravel_network:
        driver: bridge
